name: glug_app
description: The official app for the GNU LInux Users&#x27; Group NITDGP

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.3
  http: ^0.13.6
  dio: ^5.1.2
  rxdart: ^0.27.7
  date_format: ^2.0.7
  flutter_html: ^2.2.1
  firebase_messaging:
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  timeago: ^3.4.0
  characters: ^1.0.0
  sqflite: any
  path_provider:
  cached_network_image: ^3.2.3
  connectivity: ^3.0.6
  flutter_pdfview: ^1.0.0+10
  url_launcher: ^6.1.11
  flutter_linkify: ^6.0.0
  flutter_spinkit: ^5.2.0
  random_words: ^1.0.2
  progress_dialog: ^1.2.4
  double_back_to_close_app: ^2.1.0
  intro_slider: ^4.2.0
  dynamic_themes: ^1.1.0
  shared_preferences:
  flare_loading: ^3.0.0
  permission_handler: ^10.2.0
  flutter_inappwebview: ^5.7.2+3
  sizer:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #   To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran-Regular.ttf
        - asset: fonts/Catamaran-Black.ttf
          weight: 900
        - asset: fonts/Catamaran-Bold.ttf
          weight: 700
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
    - family: Nexa-Bold
      fonts:
        - asset: fonts/Nexa-Bold.otf
        - weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
